name: Deploy Snowflake

on:
  push:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      target:
        description: "Deploy target environment"
        type: choice
        required: true
        default: staging
        options: [ staging, prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    # Bind to the correct GitHub Environment (cannot reference env.* here)
    environment:
      name: ${{ github.event_name == 'workflow_dispatch' && inputs.target || 'staging' }}

    # Expose the selected env to steps
    env:
      TARGET_ENV: ${{ github.event_name == 'workflow_dispatch' && inputs.target || 'staging' }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps and snowsql
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update -y
          sudo apt-get install -y snowsql

      - name: Select env file
        id: pick
        shell: bash
        run: |
          if [ "$TARGET_ENV" = "prod" ]; then
            echo "ENV_FILE=env/prod.yaml" >> "$GITHUB_OUTPUT"
          else
            echo "ENV_FILE=env/staging.yaml" >> "$GITHUB_OUTPUT"
          fi

      - name: Render SQL
        shell: bash
        run: |
          python scripts/render.py "$TARGET_ENV" "${{ steps.pick.outputs.ENV_FILE }}" databases.yaml rendered

      - name: Apply to Snowflake
        shell: bash
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
        run: ./scripts/apply.sh "$TARGET_ENV" rendered
